---
# -----------
#   Portage
# -----------
portage_tools:
  # - app-portage/pfl # Commented because it requires USE changes
  - app-portage/flaggie
  - app-portage/eix
  - app-portage/repoman
  - app-portage/mirrorselect
  - app-portage/genlop
  - app-portage/cpuid2cpuflags
  - app-portage/elogv
  - app-portage/gentoolkit

portage_overlays:
  - lto-overlay
  - mv
